import React from 'react';
import { PageRoute } from '../types';
import { AlertCircle, ArrowRight } from 'lucide-react';
import { AdPlaceholder } from '../components/AdPlaceholder';

interface DisclaimerPageProps {
  onNavigate: (route: PageRoute) => void;
}

export const DisclaimerPage: React.FC<DisclaimerPageProps> = ({ onNavigate }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 space-y-8">
      <div className="bg-white rounded-3xl p-6 sm:p-10 border border-slate-200/90 shadow-xs space-y-6">
        <div className="border-b border-slate-100 pb-6">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-50 text-amber-700 text-xs font-bold mb-3">
            <AlertCircle className="w-4 h-4 text-amber-600" />
            <span>Legal Disclaimer</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 tracking-tight">
            Website Disclaimer
          </h1>
          <p className="text-xs text-slate-500 mt-2 font-mono">
            Last Updated: [DATE]
          </p>
        </div>

        <div className="prose prose-slate max-w-none text-slate-600 text-sm sm:text-base leading-relaxed space-y-6">
          <section className="space-y-2">
            <h2 className="text-xl font-bold text-slate-900">1. Informational Purposes Only</h2>
            <p>
              All calculation outputs, time breakdowns, statistics, and birthday information provided by the <strong>Age Calculator</strong> website are for general informational and educational convenience only.
            </p>
          </section>

          <section className="p-4 rounded-2xl bg-amber-50/80 border border-amber-200 text-amber-900 space-y-2">
            <h2 className="text-lg font-bold flex items-center gap-2">
              <AlertCircle className="w-5 h-5 text-amber-600 shrink-0" />
              <span>Not an Official Government Verification Service</span>
            </h2>
            <p className="text-xs text-amber-800 leading-relaxed">
              This website is a free, independent online tool. It is NOT an official government agency, legal age verification authority, or official identity validator. Do not rely solely on this tool for official passport applications, legal identity verification, court filings, or government filings where certified birth certificates or official records are required.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-bold text-slate-900">2. Not Legal, Medical, or Financial Advice</h2>
            <p>
              The content and calculations on this website do not constitute legal, medical, financial, or tax advice. Always consult a qualified professional when making important legal, health, or financial decisions dependent on age thresholds.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-bold text-slate-900">3. Verification of Results</h2>
            <p>
              While our calculation algorithms are thoroughly tested against standard Gregorian calendar rules, users should independently verify results when exact timing is critical for official deadlines or contractual obligations.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-bold text-slate-900">4. Limitation of Owner Responsibility</h2>
            <p>
              The website owner and operators are not responsible or liable for any errors, omissions, or decisions made based on the results generated by this Age Calculator.
            </p>
          </section>
        </div>

        <div className="pt-4 border-t border-slate-100 flex justify-end">
          <button
            onClick={() => onNavigate('/age-calculator')}
            className="px-5 py-2.5 bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs rounded-xl flex items-center gap-2 shadow-sm"
          >
            <span>Back to Age Calculator</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>

      <AdPlaceholder slotId="8001" format="horizontal" />
    </div>
  );
};
